<?xml version="1.0" ?>
<robot name="one_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="0.6"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="2.5"/>
  <xacro:property name="base_mass" value="15.0"/>

  <!-- Materials -->
  <material name="red">
    <color rgba="1 0.156 0 1"/>
  </material>

  <material name="blue">
    <color rgba="0.25 0.41 0.88 1"/>
  </material>

  <material name="green">
    <color rgba="0.2 0.8 0.2 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="black_lidar">
    <color rgba="0 0 0 0.8"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}"
               ixy="0"
               ixz="0"
               iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}"
               iyz="0"
               izz="${(1/12) * base_mass * (base_width*base_width + base_length*base_length)}"/>
    </inertial>
  </link>

  <!-- Camera Link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0.05 0 0.025" rpy="0 0 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0.05 0 0.025" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Lidar Support Link -->
  <link name="lidar_support_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 0.025"/>
      </geometry>
      <origin xyz="0 0 0.0125" rpy="0 0 0"/>
      <material name="black_lidar"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.2 0.025"/>
      </geometry>
      <origin xyz="0 0 0.0125" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0125" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Lidar Link -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.1" length="0.05"/>
      </geometry>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.1" length="0.05"/>
      </geometry>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Wheel Links -->
  <xacro:macro name="wheel_link" params="name">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 ixy="0"
                 ixz="0"
                 iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 iyz="0"
                 izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:wheel_link name="left_wheel_front"/>
  <xacro:wheel_link name="left_wheel_back"/>
  <xacro:wheel_link name="right_wheel_front"/>
  <xacro:wheel_link name="right_wheel_back"/>

  <!-- Joints -->
  <joint name="base_wheel_left_front" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_front"/>
    <origin xyz="0.15 0.225 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_wheel_left_back" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_back"/>
    <origin xyz="-0.15 0.225 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_wheel_right_front" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_front"/>
    <origin xyz="0.15 -0.225 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_wheel_right_back" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_back"/>
    <origin xyz="-0.15 -0.225 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Camera Joint - positioned at front of robot, angled down -->
  <joint name="base_to_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.25 0 0.15" rpy="0 0.3 0"/>
  </joint>

  <joint name="base_to_lidar_support" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_support_link"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
  </joint>

  <joint name="lidar_rotation_joint" type="fixed">
    <parent link="lidar_support_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.025" rpy="0 0 0"/>
  </joint>

  <!-- Include Gazebo configurations -->
  <xacro:include filename="$(find boffin_robot)/urdf/one_robot.gazebo"/>

</robot>